@extends('layouts.app')
@section('title', 'Dashboard')
@section('content')
<section class="dashboard-intro"><div><p class="overline">Overview</p><h1>Welcome back, {{ auth()->user()->name }}</h1><p>Here's what's happening with your wedding invitations today.</p></div><a class="primary-button" href="{{ route('admin.customers.index', ['status' => 'pending']) }}"><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>Review Pending Users</a></section>

<section class="metric-grid" aria-label="Dashboard statistics">
    <article class="metric-card"><span class="metric-icon gold"><svg viewBox="0 0 24 24"><path d="M4 5h16v14H4zM4 7l8 6 8-6"/></svg></span><div><p>Total Invitations</p><strong>{{ number_format($statistics['invitations']) }}</strong><small>Across all customers</small></div></article>
    <article class="metric-card"><span class="metric-icon green"><svg viewBox="0 0 24 24"><path d="M16 20v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8M17 11l2 2 4-4"/></svg></span><div><p>Active Customers</p><strong>{{ number_format($statistics['active_customers']) }}</strong><small class="positive">Approved accounts</small></div></article>
    <article class="metric-card"><span class="metric-icon blue"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/></svg></span><div><p>Published Invitations</p><strong>{{ number_format($statistics['published_invitations']) }}</strong><small>Currently available online</small></div></article>
    <article class="metric-card"><span class="metric-icon rose"><svg viewBox="0 0 24 24"><path d="M5 3v3M19 3v3M4 8h16M5 5h14a2 2 0 0 1 2 2v13H3V7a2 2 0 0 1 2-2Z"/><path d="m8 14 2 2 5-5"/></svg></span><div><p>New RSVPs</p><strong>{{ number_format($statistics['new_rsvps']) }}</strong><small>Received in the last 7 days</small></div></article>
</section>

<div class="dashboard-content-grid">
    <section class="panel recent-panel" id="recent-invitations"><div class="panel-header"><div><h2>Recent Invitations</h2><p>Latest invitations created by customers.</p></div><a href="{{ route('admin.invitations.index') }}">View all <svg viewBox="0 0 24 24"><path d="M5 12h14M14 7l5 5-5 5"/></svg></a></div><div class="table-scroll"><table class="premium-table"><thead><tr><th>Couple</th><th>Template</th><th>Status</th><th>Date</th><th><span class="sr-only">Action</span></th></tr></thead><tbody>@forelse($recentInvitations as $invitation)<tr data-searchable="{{ Str::lower($invitation->title.' '.$invitation->user->name.' '.$invitation->template->name) }}"><td><div class="couple-cell"><span>{{ mb_strtoupper(mb_substr($invitation->title, 0, 1)) }}</span><div><strong>{{ $invitation->title }}</strong><small>{{ $invitation->user->name }}</small></div></div></td><td>{{ $invitation->template->name }}</td><td><span class="status-badge {{ $invitation->status }}"><i></i>{{ ucfirst($invitation->status) }}</span></td><td>{{ $invitation->created_at->format('d M Y') }}</td><td class="table-action">@if($invitation->status === 'published')<a href="{{ route('public.invitation', $invitation->slug) }}" target="_blank" aria-label="Open {{ $invitation->title }}"><svg viewBox="0 0 24 24"><path d="M14 3h7v7M10 14 21 3M21 14v6a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h6"/></svg></a>@else<span>—</span>@endif</td></tr>@empty<tr><td colspan="5"><div class="table-empty">No invitations have been created yet.</div></td></tr>@endforelse</tbody></table></div></section>

    <aside class="dashboard-side-stack">
        <section class="panel compact-panel"><div class="panel-header"><div><h2>Quick Actions</h2><p>Common administration tasks.</p></div></div><div class="quick-actions"><a href="{{ route('admin.customers.index', ['status'=>'pending']) }}"><span class="metric-icon gold"><svg viewBox="0 0 24 24"><path d="M16 20v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8M17 11l2 2 4-4"/></svg></span><span><strong>Review Pending Users</strong><small>{{ $statistics['pending_customers'] }} awaiting approval</small></span><svg class="action-arrow" viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></a><a href="{{ route('admin.invitations.index') }}"><span class="metric-icon blue"><svg viewBox="0 0 24 24"><path d="M4 5h16v14H4zM4 7l8 6 8-6"/></svg></span><span><strong>View Invitations</strong><small>Monitor customer invitations</small></span><svg class="action-arrow" viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></a></div></section>
        <section class="panel compact-panel"><div class="panel-header"><div><h2>Recent Activity</h2><p>Latest workspace updates.</p></div></div><div class="activity-list">@if($recentRsvp)<article><span class="activity-dot green"></span><div><p><strong>New RSVP</strong> from {{ $recentRsvp->guest_name }}</p><small>{{ $recentRsvp->invitation->title }} · {{ $recentRsvp->created_at->diffForHumans() }}</small></div></article>@endif @if($recentCustomer)<article><span class="activity-dot blue"></span><div><p><strong>New customer</strong> {{ $recentCustomer->name }}</p><small>Registered {{ $recentCustomer->created_at->diffForHumans() }}</small></div></article>@endif @if($recentWish)<article><span class="activity-dot rose"></span><div><p><strong>Wish received</strong> from {{ $recentWish->guest_name }}</p><small>{{ $recentWish->invitation->title }} · {{ $recentWish->created_at->diffForHumans() }}</small></div></article>@endif @if(!$recentRsvp && !$recentCustomer && !$recentWish)<div class="activity-empty">Activity will appear here.</div>@endif</div></section>
    </aside>
</div>
@endsection
