@php
    $data = old() ?: ($invitation?->data ?? []);
    $events = old('events', data_get($data, 'events', []));
    $stories = old('stories', data_get($data, 'stories', []));
    $banks = old('banks', data_get($data, 'banks', []));
@endphp
<section class="card form-section"><h2>Identitas undangan</h2><div class="form-grid">
    <div class="field"><label for="template_id">Template</label><select class="input" id="template_id" name="template_id" required><option value="">Pilih template</option>@foreach($templates as $template)<option value="{{ $template->id }}" @selected((string)old('template_id', $invitation?->template_id) === (string)$template->id)>{{ $template->name }}</option>@endforeach</select></div>
    <div class="field"><label for="title">Judul</label><input class="input" id="title" name="title" data-title-source value="{{ old('title', $invitation?->title) }}" placeholder="Alexander & Cyntia" required></div>
    <div class="field full"><label for="slug">Slug link</label><input class="input" id="slug" name="slug" data-slug-target value="{{ old('slug', $invitation?->slug) }}" placeholder="alexander-cyntia" required><span class="muted">Link publik: domain.com/<strong>slug</strong></span></div>
</div></section>
<div class="grid invitation-list">
<section class="card form-section"><div class="eyebrow">The Groom</div><h2>Mempelai pria</h2>
    @foreach(['nickname'=>'Nama panggilan','full_name'=>'Nama lengkap','father'=>'Nama ayah','mother'=>'Nama ibu','instagram'=>'Instagram'] as $key=>$label)<div class="field"><label for="groom_{{ $key }}">{{ $label }}</label><input class="input" id="groom_{{ $key }}" name="groom[{{ $key }}]" value="{{ old('groom.'.$key, data_get($data, 'groom.'.$key)) }}" @required(in_array($key,['nickname','full_name']))></div>@endforeach
    <div class="field"><label for="groom_photo">Foto pria</label><input class="input" id="groom_photo" type="file" name="groom_photo" accept="image/jpeg,image/png,image/webp"></div>
</section>
<section class="card form-section"><div class="eyebrow">The Bride</div><h2>Mempelai wanita</h2>
    @foreach(['nickname'=>'Nama panggilan','full_name'=>'Nama lengkap','father'=>'Nama ayah','mother'=>'Nama ibu','instagram'=>'Instagram'] as $key=>$label)<div class="field"><label for="bride_{{ $key }}">{{ $label }}</label><input class="input" id="bride_{{ $key }}" name="bride[{{ $key }}]" value="{{ old('bride.'.$key, data_get($data, 'bride.'.$key)) }}" @required(in_array($key,['nickname','full_name']))></div>@endforeach
    <div class="field"><label for="bride_photo">Foto wanita</label><input class="input" id="bride_photo" type="file" name="bride_photo" accept="image/jpeg,image/png,image/webp"></div>
</section></div>
<section class="card form-section"><h2>Tanggal dan quote</h2><div class="form-grid"><div class="field"><label for="wedding_date">Tanggal pernikahan</label><input class="input" id="wedding_date" type="date" name="wedding_date" value="{{ old('wedding_date', data_get($data, 'wedding_date')) }}" required></div><div class="field full"><label for="quote">Quote</label><textarea class="input" id="quote" name="quote">{{ old('quote', data_get($data, 'quote')) }}</textarea></div></div></section>
<section class="card form-section" data-repeater data-next-index="{{ count($events) }}"><div class="page-head"><h2>Events</h2><button class="button small secondary" type="button" data-add-repeater>Tambah event</button></div><div data-repeater-list>
@foreach($events as $index=>$event)<div class="repeater-item"><div class="form-grid">@foreach(['name'=>'Nama acara','date'=>'Tanggal','time'=>'Jam','location'=>'Lokasi','address'=>'Alamat','maps_url'=>'Google Maps'] as $key=>$label)<div class="field {{ in_array($key,['address','maps_url']) ? 'full' : '' }}"><label>{{ $label }}</label>@if($key==='address')<textarea class="input" name="events[{{ $index }}][{{ $key }}]">{{ $event[$key] ?? '' }}</textarea>@else<input class="input" type="{{ $key==='date' ? 'date' : ($key==='time' ? 'time' : 'text') }}" name="events[{{ $index }}][{{ $key }}]" value="{{ $event[$key] ?? '' }}">@endif</div>@endforeach</div><button class="button small danger" type="button" data-remove-repeater>Hapus</button></div>@endforeach
</div><template><div class="repeater-item"><div class="form-grid"><div class="field"><label>Nama acara</label><input class="input" name="events[__INDEX__][name]"></div><div class="field"><label>Tanggal</label><input class="input" type="date" name="events[__INDEX__][date]"></div><div class="field"><label>Jam</label><input class="input" type="time" name="events[__INDEX__][time]"></div><div class="field"><label>Lokasi</label><input class="input" name="events[__INDEX__][location]"></div><div class="field full"><label>Alamat</label><textarea class="input" name="events[__INDEX__][address]"></textarea></div><div class="field full"><label>Google Maps</label><input class="input" name="events[__INDEX__][maps_url]"></div></div><button class="button small danger" type="button" data-remove-repeater>Hapus</button></div></template></section>
<section class="card form-section" data-repeater data-next-index="{{ count($stories) }}"><div class="page-head"><h2>Love Story</h2><button class="button small secondary" type="button" data-add-repeater>Tambah cerita</button></div><div data-repeater-list>@foreach($stories as $index=>$story)<div class="repeater-item"><div class="form-grid"><div class="field"><label>Judul</label><input class="input" name="stories[{{ $index }}][title]" value="{{ $story['title'] ?? '' }}"></div><div class="field"><label>Tanggal</label><input class="input" type="date" name="stories[{{ $index }}][date]" value="{{ $story['date'] ?? '' }}"></div><div class="field full"><label>Cerita</label><textarea class="input" name="stories[{{ $index }}][story]">{{ $story['story'] ?? '' }}</textarea></div></div><button class="button small danger" type="button" data-remove-repeater>Hapus</button></div>@endforeach</div><template><div class="repeater-item"><div class="form-grid"><div class="field"><label>Judul</label><input class="input" name="stories[__INDEX__][title]"></div><div class="field"><label>Tanggal</label><input class="input" type="date" name="stories[__INDEX__][date]"></div><div class="field full"><label>Cerita</label><textarea class="input" name="stories[__INDEX__][story]"></textarea></div></div><button class="button small danger" type="button" data-remove-repeater>Hapus</button></div></template><div class="field"><label>Foto story (urutan mengikuti cerita)</label><input class="input" type="file" name="story_photos[]" accept="image/jpeg,image/png,image/webp" multiple></div></section>
<section class="card form-section" data-repeater data-next-index="{{ count($banks) }}"><div class="page-head"><h2>Wedding Gift</h2><button class="button small secondary" type="button" data-add-repeater>Tambah rekening</button></div><div data-repeater-list>@foreach($banks as $index=>$bank)<div class="repeater-item"><div class="form-grid">@foreach(['bank_name'=>'Bank','account_number'=>'Nomor rekening','account_name'=>'Nama pemilik'] as $key=>$label)<div class="field"><label>{{ $label }}</label><input class="input" name="banks[{{ $index }}][{{ $key }}]" value="{{ $bank[$key] ?? '' }}"></div>@endforeach</div><button class="button small danger" type="button" data-remove-repeater>Hapus</button></div>@endforeach</div><template><div class="repeater-item"><div class="form-grid"><div class="field"><label>Bank</label><input class="input" name="banks[__INDEX__][bank_name]"></div><div class="field"><label>Nomor rekening</label><input class="input" name="banks[__INDEX__][account_number]"></div><div class="field"><label>Nama pemilik</label><input class="input" name="banks[__INDEX__][account_name]"></div></div><button class="button small danger" type="button" data-remove-repeater>Hapus</button></div></template></section>
<section class="card form-section"><h2>Media</h2><div class="form-grid"><div class="field"><label>Cover</label><input class="input" type="file" name="cover" accept="image/jpeg,image/png,image/webp"></div><div class="field"><label>QRIS</label><input class="input" type="file" name="qris" accept="image/jpeg,image/png,image/webp"></div><div class="field"><label>Music</label><input class="input" type="file" name="music" accept="audio/mpeg,audio/ogg,audio/wav"></div><div class="field full" data-repeater data-next-index="1"><label>Gallery</label><div data-repeater-list><div class="repeater-item"><input class="input" type="file" name="gallery[]" accept="image/jpeg,image/png,image/webp"></div></div><button class="button small secondary" type="button" data-add-repeater>Tambah foto</button><template><div class="repeater-item"><input class="input" type="file" name="gallery[]" accept="image/jpeg,image/png,image/webp"><button class="button small danger" type="button" data-remove-repeater>Hapus</button></div></template></div></div></section>
<section class="card form-section"><h2>Pengaturan section</h2><div class="check-grid">@foreach(['countdown'=>'Countdown','gallery'=>'Gallery','story'=>'Love Story','gift'=>'Wedding Gift','rsvp'=>'RSVP','wishes'=>'Wishes','music'=>'Music'] as $key=>$label)<label class="check"><input type="checkbox" name="settings[{{ $key }}]" value="1" @checked((bool)old('settings.'.$key, data_get($data, 'settings.'.$key, true)))> {{ $label }}</label>@endforeach</div></section>
<div class="actions"><button class="button gold" type="submit">Simpan undangan</button><a class="button secondary" href="{{ route('dashboard') }}">Kembali</a></div>
